const Order = require('../models/OrderSchema');
const { generateReceiptBuffer } = require('../utils/pdf/pdf');
const pdfService = require('../services/pdfService');

// Create a new order
const createOrder = async (req, res) => {
  try {
    const {
      customer,
      selections,
      promo,
      payment,
      notes,
      salesperson,
      storeLocation,
      status
    } = req.body;

    console.log({
      customer,
      selections,
      promo,
      payment,
      notes,
      salesperson,
      storeLocation,
      status
    })

    // Validate required fields
    if (!customer || !customer.name) {
      return res.status(400).json({
        success: false,
        error: 'Customer name is required'
      });
    }

    if (!selections || selections.length === 0) {
      return res.status(400).json({
        success: false,
        error: 'At least one selection is required'
      });
    }

    if (!payment || !payment.method || !payment.amount) {
      return res.status(400).json({
        success: false,
        error: 'Payment method and amount are required'
      });
    }

    // Calculate pricing from selections
    const subtotal = selections.reduce((total, selection) => {
      return total + (selection.selectionPrice || 0);
    }, 0);

    const discount = promo ? (promo.appliedDiscount || 0) : 0;
    const totalPrice = subtotal - discount;

    // Create the order
    const order = new Order({
      customer,
      selections,
      promo,
      payment,
      pricing: {
        subtotal,
        discount,
        totalPrice,
        tax: 0,
        shipping: 0
      },
      notes,
      salesperson,
      storeLocation,
      status
    });

    // Order ID will be automatically generated by the schema pre-save middleware

    // Save the order
    const savedOrder = await order.save();
    console.log({ savedOrder })

    res.status(201).json({
      success: true,
      order: savedOrder,
      message: 'Order created successfully'
    });

  } catch (error) {
    console.error('Error creating order:', error);

    // Provide more detailed error information
    let errorMessage = 'Failed to create order';
    if (error.name === 'ValidationError') {
      errorMessage = 'Validation error: ' + Object.values(error.errors).map(err => err.message).join(', ');
    } else if (error.code === 11000) {
      errorMessage = 'Duplicate order ID';
    }

    res.status(500).json({
      success: false,
      error: errorMessage,
      details: error.message
    });
  }
};

// Get all orders with pagination and filtering
const getOrders = async (req, res) => {
  try {
    const {
      page = 1,
      limit = 10,
      status,
      customerName,
      startDate,
      endDate,
      sortBy = 'orderDate',
      sortOrder = 'desc'
    } = req.query;

    // Build filter object
    const filter = {};

    if (status) {
      filter.status = status;
    }

    if (customerName) {
      filter['customer.name'] = { $regex: customerName, $options: 'i' };
    }

    if (startDate || endDate) {
      filter.orderDate = {};
      if (startDate) filter.orderDate.$gte = new Date(startDate);
      if (endDate) filter.orderDate.$lte = new Date(endDate);
    }

    // Build sort object
    const sort = {};
    sort[sortBy] = sortOrder === 'desc' ? -1 : 1;

    // Calculate skip value for pagination
    const skip = (parseInt(page) - 1) * parseInt(limit);

    // Execute query
    const orders = await Order.find(filter)
      .sort(sort)
      .skip(skip)
      .limit(parseInt(limit));

    // Get total count for pagination
    const total = await Order.countDocuments(filter);

    res.json({
      success: true,
      orders,
      total,
      page: parseInt(page),
      limit: parseInt(limit),
      totalPages: Math.ceil(total / parseInt(limit))
    });

  } catch (error) {
    console.error('Error fetching orders:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch orders',
      details: error.message
    });
  }
};

// Get a single order by ID
const getOrderById = async (req, res) => {
  try {
    const { id } = req.params;

    const order = await Order.findById(id);

    if (!order) {
      return res.status(404).json({
        success: false,
        error: 'Order not found'
      });
    }

    res.json({
      success: true,
      order
    });

  } catch (error) {
    console.error('Error fetching order:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch order',
      details: error.message
    });
  }
};

// Get order by orderId
const getOrderByOrderId = async (req, res) => {
  try {
    const { orderId } = req.params;

    const order = await Order.findOne({ orderId });

    if (!order) {
      return res.status(404).json({
        success: false,
        error: 'Order not found'
      });
    }

    res.json({
      success: true,
      order
    });

  } catch (error) {
    console.error('Error fetching order:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to fetch order',
      details: error.message
    });
  }
};

// Update an order
// const updateOrder = async (req, res) => {
//   try {
//     const { id } = req.params;
//     const updateData = req.body;

//     // Remove fields that shouldn't be updated directly
//     delete updateData._id;
//     delete updateData.orderId;
//     delete updateData.createdAt;

//     const order = await Order.findByIdAndUpdate(
//       id,
//       { ...updateData, updatedAt: new Date() },
//       { new: true, runValidators: true }
//     );

//     if (!order) {
//       return res.status(404).json({
//         success: false,
//         error: 'Order not found'
//       });
//     }

//     res.json({
//       success: true,
//       order,
//       message: 'Order updated successfully'
//     });

//   } catch (error) {
//     console.error('Error updating order:', error);
//     res.status(500).json({
//       success: false,
//       error: 'Failed to update order',
//       details: error.message
//     });
//   }
// };

// Delete an order
const deleteOrder = async (req, res) => {
  try {
    const { id } = req.params;

    const order = await Order.findByIdAndDelete(id);

    if (!order) {
      return res.status(404).json({
        success: false,
        error: 'Order not found'
      });
    }

    res.json({
      success: true,
      message: 'Order deleted successfully'
    });

  } catch (error) {
    console.error('Error deleting order:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to delete order',
      details: error.message
    });
  }
};

// Update order status
const updateOrderStatus = async (req, res) => {
  try {
    console.log("called status change")
    const { id } = req.params;
    const { status } = req.body;

    if (!status) {
      return res.status(400).json({
        success: false,
        error: 'Status is required'
      });
    }

    const validStatuses = ['pending', 'confirmed', 'processing', 'completed', 'cancelled', 'refunded'];
    if (!validStatuses.includes(status)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid status value'
      });
    }

    const order = await Order.findByIdAndUpdate(
      id,
      { status },
      { new: true, runValidators: true }
    );

    if (!order) {
      return res.status(404).json({
        success: false,
        error: 'Order not found'
      });
    }

    res.json({
      success: true,
      order,
      message: `Order status updated to ${status}`
    });

  } catch (error) {
    console.error('Error updating order status:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to update order status',
      details: error.message
    });
  }
};

// Search orders by customer name or order ID
const searchOrders = async (req, res) => {
  try {
    const { query } = req.query;

    if (!query) {
      return res.status(400).json({
        success: false,
        error: 'Search query is required'
      });
    }

    const orders = await Order.find({
      $or: [
        { 'customer.name': { $regex: query, $options: 'i' } },
        { orderId: { $regex: query, $options: 'i' } }
      ]
    })
      .sort({ orderDate: -1 })
      .limit(20);

    res.json({
      success: true,
      orders,
      total: orders.length
    });

  } catch (error) {
    console.error('Error searching orders:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to search orders',
      details: error.message
    });
  }
};

// Generate and download PDF receipt for an order (on-demand, no storage)
const generateReceipt = async (req, res) => {
  try {
    const { id } = req.params;

    const order = await Order.findById(id);

    if (!order) {
      return res.status(404).json({
        success: false,
        error: 'Order not found'
      });
    }

    // Generate PDF in memory
    // const pdfBuffer = await pdfService.generateReceiptBuffer(order);
    const pdfBuffer = await generateReceiptBuffer(order);

    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="receipt-${order.orderId}.pdf"`);
    res.setHeader('Content-Length', pdfBuffer.length);

    // Send the PDF buffer directly to the client
    res.send(pdfBuffer);

  } catch (error) {
    console.error('Error generating receipt:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to generate receipt',
      details: error.message
    });
  }
};



module.exports = {
  createOrder,
  getOrders,
  getOrderById,
  getOrderByOrderId,
  deleteOrder,
  updateOrderStatus,
  searchOrders,
  generateReceipt
};
